env:
  browser: true
  es2021: true
  jasmine: true
extends:
  - standard
  - 'plugin:jasmine/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
  - jasmine
rules: {}
